[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "privateer"
dynamic = ["version"]
description = "Tool to back up docker volumes onto remote machines"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = []
authors = [
  { name = "Rich FitzJohn", email = "r.fitzjohn@imperial.ac.uk" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "click",
    "cryptography>=3.1",
    "docker",
    "docopt-ng",
    "hvac",
    "pydantic",
    "tzlocal",
    "yacron"
]

[project.urls]
Documentation = "https://github.com/reside-ic/privateer#readme"
Issues = "https://github.com/reside-ic/privateer/issues"
Source = "https://github.com/reside-ic/privateer"

[project.scripts]
privateer = "privateer.cli:cli"

[tool.hatch.version]
path = "src/privateer/__about__.py"

[tool.hatch.envs.default]
python = "python3"
dependencies = [
  "coverage[toml]>=6.5",
  "pytest",
  "pytest-mock",
  "vault-dev>=0.1.1"
]
[tool.hatch.envs.default.scripts]
test = "pytest {args:tests}"
test-cov = "coverage run -m pytest {args:tests}"
cov-report = [
  "- coverage combine",
  "coverage report --show-missing",
]
cov = [
  "test-cov",
  "cov-report",
]
cov-report-xml = [
  "- coverage combine",
  "coverage xml",
]
cov-ci = [
  "test-cov",
  "cov-report-xml",
]

[[tool.hatch.envs.all.matrix]]
python = ["3.10", "3.11", "3.12", "3.13"]

[tool.hatch.envs.lint]
extra-dependencies = [
  "black>=23.1.0",
  "mypy>=1.0.0",
  "ruff>=0.0.243",
]
[tool.hatch.envs.lint.scripts]
typing = "mypy --install-types --non-interactive {args:src/privateer tests}"
style = [
  "ruff check {args:.}",
  "black --check --diff {args:.}",
]
fmt = [
  "black {args:.}",
  "ruff check --fix {args:.}",
  "style",
]
all = [
  "style",
  "typing",
]

[tool.black]
line-length = 80
skip-string-normalization = true

[tool.ruff]
line-length = 80

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = [
  "A",
  "ARG",
  "B",
  "C",
  "DTZ",
  "E",
  "EM",
  "F",
  "FBT",
  "I",
  "ICN",
  "ISC",
  "N",
  "PLC",
  "PLE",
  "PLR",
  "PLW",
  "Q",
  "RUF",
  "S",
  "T",
  "TID",
  "UP",
  "W",
  "YTT",
]
ignore = [
  "A002",
  # Allow non-abstract empty methods in abstract base classes
  "B027",
  # Don't require docstrings everywhere for now
  "D100", "D101", "D102", "D103", "D104", "D105", "D107",
  # Allow boolean positional values in function calls, like `dict.get(... True)`
  "FBT003",
  # Ignore checks for possible passwords
  "S105", "S106", "S107",
  # Ignore complexity
  "C901", "PLR0911", "PLR0912", "PLR0913", "PLR0915",
  # Let us use random
  "S311",
  # Let us use print
  "T201"
]
unfixable = [
  # Don't touch unused imports
  "F401",
]

[tool.ruff.lint.isort]
known-first-party = ["privateer"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.per-file-ignores]
# Tests can use magic values, assertions, and relative imports
"tests/**/*" = ["PLR2004", "S101", "TID252"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.coverage.run]
source_pkgs = ["privateer", "tests"]
branch = true
parallel = true
omit = [
  "src/privateer/__about__.py",
]

[tool.coverage.paths]
privateer = ["src/privateer", "*/privateer/src/privateer"]
tests = ["tests", "*/privateer/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.mypy]
exclude = ["docker"]

[[tool.mypy.overrides]]
module = "vault_dev"
ignore_missing_imports = true

[tool.hatch.envs.docs]
extra-dependencies = [
  "mkdocs-click",
  "mkdocs-material",
  "mkdocs-spellcheck[all]",
  "mkdocstrings-python",
]

[tool.hatch.envs.docs.scripts]
build = "mkdocs build {args}"
serve = "mkdocs serve {args}"
